### ISSUE TITLE
Gem file is all funked up

### ISSUE THREAD

**Issue by whatstheward** [learn-co-curriculum/rails-index-show-new-create-lab#16]
Had to switch sqlite version in gemfile and install an old version of bundler to get gem files installed

**Comment by RylanBauermeister** [comment]
Seconding this!  For other students encountering it, here's the workaround until a patch is put in:

First, go into the gem file and change line 7 to:
`gem 'sqlite3', '~> 1.3.6'`

On the command line, run:
`gem install bundler --version=1.9.0`
followed by:
'bundle _1.9.0_ install'

That should work, and should let you get around uninstalling your current bundler version.

**Comment by maxwellbenton** [comment]
Hi @whatstheward and @RylanBauermeister,

Thank you for spotting this and providing feedback. We've updated the gemfile so that it contains sqlite3 ~>1.3.6 as well as Rails 5.0.7.1 to be consistent with other labs. This lab's gemfile.lock is also now set to use bundler 2. Future students should not see these issues going forward.

Thank you for contributing to a learn.co lesson and for helping to make the materials better for future students!
