### ISSUE TITLE
missing secrets.yml

### ISSUE THREAD

**Issue by tejbans** [learn-co-curriculum/rails-index-show-new-create-lab#3]
Hello.get an error when running my tests.

Missing `secret_token` and `secret_key_base` for 'test' environment, set these values in `config/secrets.yml`.

**Comment by aturkewi** [comment]
@jmburges @PeterBell 

Hey Joe, I noticed you added the secrets.yml file to the .gitignore in a commit at the end of the year and it looks like this is causing issues. Should we be add it back? Or perhaps adding a hint to the students to create their own?

**Comment by jmburges** [comment]
yeah put it back in!

**Comment by PeterBell** [comment]
Hey @jmburges and @aturkewi I'm gonna suggest we follow more production like best practices if you're cool with that so we don't teach students bad habits. Let's keep the config/secrets.yml in the .gitconfig. Otherwise they'll end up committing their secrets which in a real world project would be bad.

Let's add a config/secrets-template.yml with an instruction for the local user to rename - I'll submit a PR today for 👀  . . .

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/rails-index-show-new-create-lab/commit/7651de3ecdff06a4527e760b96262b5411f423ee
